### PR TITLE
persistent queue

### PR DESCRIPTION
**Pull request by gaucheclement**

### CODE REVIEW

**Comment by jaymoulin** [comment]
BTW, I don't see unit test with your PR

**Comment by Joyam** [comment]
A new branch 6.X was created for this "fix".

It is specific to an old project and it does not have to be put into the main project.

Changes must be more generic...

**Comment by jaymoulin** [comment]
https://github.com/Logi-CE/fmup/releases

Release note please

**Comment by Joyam** [comment]
Done.

**Pull request closed without merging**
