### PR TITLE
Persistent queue

### PR DESCRIPTION
**Pull request by gaucheclement**
Persistent queue

### CODE REVIEW

**Comment by jaymoulin** [comment]
17 commits seems a bit overkill. Most of those aren't yours BTW. You probably have to rebase this one

**Comment by gaucheclement** [comment]
This is an evolution of 6.17.4, but I can only make a pull request on the master. What can I do ? Rebase master ?

**Comment by jaymoulin** [comment]
You should propose 2 fixes if you want the 6.x tag to evolve.

- A branch with a living and maintained 6.x codebase
- A PR on master with your fix only rebased on master.

Anyway, You better consider upgrading to 7.x to avoid this to happen

**Comment by gaucheclement** [comment]
I can't create branch on fmup

**Comment by jaymoulin** [comment]
`git checkout -b 6.x 6.17.4 && git push -u origin 6.x`

**Comment by jaymoulin** [comment]
BTW, I don't see unit test with your PR

**Comment by gaucheclement** [comment]
Basculement sur la nouvelle branche '6.17.5'
ERROR: Permission to Logi-CE/fmup.git denied to gaucheclement.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

**Pull request closed without merging**
